#!/usr/bin/perl
use warnings;
use strict;
use CGI;
use Net::OAuth2::Client;
use utf8;
use LWP::Simple;
use Data::Dumper;

my $v密码文件 = "../密码文件";
open (RD, "<$v密码文件") or die "Cannot open file $v密码文件 来读取";
my ($app_key, $app_secret) = <RD>;
chomp $app_key;
chomp $app_secret;
close RD;

my $access_token;
my $q = CGI->new;
my $code = $q->param("code");
my %config = (
    name => '新浪微博',
    client_id => $app_key,
    client_secret => $app_secret,
    site => 'https://api.weibo.com',
    authorize_path => '/oauth2/authorize',
    access_token_path => '/oauth2/access_token',
    redirect_uri => "http://sinatag.bikouchan.org/cgi-bin/callback");

my $auth = Net::OAuth2::Profile::WebServer->new(%config);

$access_token = $auth->get_access_token($code);
#my $v回应 = $access_token->get('https://api.weibo.com/2/statuses/user_timeline.json&screen_name=哈哈');
#$v回应->is_success or die "Something Error: " . $v回应->status_line;
print $q->header;
print $q->start_html;
#print "Yay, it worked:" . $v回应->decoded_content;
#print Dumper($access_token);
#my $v下载 = get("https://api.weibo.com/2/statuses/user_timeline.json");
#if ($v下载->is_success){
#    print $v下载->content;
# }
# else{
#     print "没有成功下载到内容";
# }
print "Just a test ";
print $access_token->{NOA_access_token};
print $q->end_html;
